/**
 * completions.ts — Generate shell completion scripts for bash/zsh
 *
 * Usage:
 *   eval "$(wangchuan completions bash)"   # add to .bashrc
 *   eval "$(wangchuan completions zsh)"    # add to .zshrc
 */

import { logger } from '../utils/logger.js';
import { t }      from '../i18n.js';

const COMMANDS = [
  'init', 'pull', 'push', 'status', 'diff', 'list', 'dump', 'lang',
  'sync', 'watch', 'env', 'agent', 'key', 'report', 'doctor', 'history',
  'snapshot', 'summary', 'setup', 'health', 'search', 'config',
  'changelog', 'tag', 'cleanup', 'template', 'batch', 'completions',
];

const AGENTS = 'openclaw claude gemini codebuddy workbuddy cursor';

const BASH_SCRIPT = `# wangchuan bash completion — generated by wangchuan completions bash
_wangchuan() {
  local cur prev commands agents
  COMPREPLY=()
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"
  commands="${COMMANDS.join(' ')}"
  agents="${AGENTS}"

  case "\${prev}" in
    -a|--agent)
      COMPREPLY=( $(compgen -W "\${agents}" -- "\${cur}") )
      return 0
      ;;
    completions)
      COMPREPLY=( $(compgen -W "bash zsh" -- "\${cur}") )
      return 0
      ;;
    env)
      COMPREPLY=( $(compgen -W "list use create delete" -- "\${cur}") )
      return 0
      ;;
    agent)
      COMPREPLY=( $(compgen -W "list enable disable set-path info" -- "\${cur}") )
      return 0
      ;;
    key)
      COMPREPLY=( $(compgen -W "show export import rotate" -- "\${cur}") )
      return 0
      ;;
    snapshot)
      COMPREPLY=( $(compgen -W "create restore list delete" -- "\${cur}") )
      return 0
      ;;
    config)
      COMPREPLY=( $(compgen -W "export import validate" -- "\${cur}") )
      return 0
      ;;
    tag)
      COMPREPLY=( $(compgen -W "add remove list find" -- "\${cur}") )
      return 0
      ;;
    template)
      COMPREPLY=( $(compgen -W "list apply" -- "\${cur}") )
      return 0
      ;;
    lang)
      COMPREPLY=( $(compgen -W "zh en" -- "\${cur}") )
      return 0
      ;;
  esac

  if [[ \${COMP_CWORD} -eq 1 ]]; then
    COMPREPLY=( $(compgen -W "\${commands}" -- "\${cur}") )
    return 0
  fi

  case "\${cur}" in
    -*)
      local opts="-a --agent -h --help"
      case "\${COMP_WORDS[1]}" in
        push)  opts="\${opts} -m --message -n --dry-run -o --only -x --exclude" ;;
        pull)  opts="\${opts} -o --only -x --exclude" ;;
        sync)  opts="\${opts} -n --dry-run -o --only -x --exclude" ;;
        init)  opts="-r --repo -k --key --force -h --help" ;;
        watch) opts="\${opts} -i --interval" ;;
        search) opts="\${opts} -i --ignore-case --regex -C --context" ;;
        report|summary) opts="--json -h --help" ;;
        history) opts="-l --limit --json -h --help" ;;
        changelog|snapshot) opts="-l --limit -h --help" ;;
        cleanup) opts="\${opts} --auto --days" ;;
        doctor) opts="--fix -h --help" ;;
        batch)  opts="--continue-on-error -h --help" ;;
      esac
      COMPREPLY=( $(compgen -W "\${opts}" -- "\${cur}") )
      return 0
      ;;
  esac
}
complete -F _wangchuan wangchuan
`;

const ZSH_SCRIPT = `#compdef wangchuan
# wangchuan zsh completion — generated by wangchuan completions zsh

_wangchuan() {
  local -a commands agents
  commands=(
    'init:Initialize Wangchuan'
    'pull:Pull configs from remote'
    'push:Push configs to remote'
    'status:Show sync status'
    'diff:Show differences'
    'list:List managed files'
    'dump:Dump config contents'
    'lang:Set display language'
    'sync:Bidirectional smart sync'
    'watch:Watch for changes'
    'env:Manage environments'
    'agent:Manage agents'
    'key:Manage encryption key'
    'report:Generate sync report'
    'doctor:Diagnose issues'
    'history:Show sync history'
    'snapshot:Manage snapshots'
    'summary:Show summary'
    'setup:Guided setup wizard'
    'health:Health check'
    'search:Search across files'
    'config:Export/import config'
    'changelog:Show commit log'
    'tag:Manage file tags'
    'cleanup:Detect stale entries'
    'template:Config templates'
    'batch:Run multiple commands'
    'completions:Generate shell completions'
  )
  agents=(openclaw claude gemini codebuddy workbuddy cursor)

  _arguments -C \\
    '1:command:->cmd' \\
    '*::arg:->args'

  case "\$state" in
    cmd)
      _describe 'command' commands
      ;;
    args)
      case "\${words[1]}" in
        push|pull|sync|status|diff|list|dump|search|cleanup|watch)
          _arguments \\
            '(-a --agent)'{-a,--agent}'[Agent name]:agent:('"${AGENTS}"')'
          ;;
        init)
          _arguments \\
            '(-r --repo)'{-r,--repo}'[Git repo URL]:url:' \\
            '(-k --key)'{-k,--key}'[Master key hex]:key:' \\
            '--force[Force reinitialize]'
          ;;
        completions)
          _arguments '1:shell:(bash zsh)'
          ;;
        lang)
          _arguments '1:language:(zh en)'
          ;;
        env)
          _arguments '1:action:(list use create delete)'
          ;;
        agent)
          _arguments '1:action:(list enable disable set-path info)'
          ;;
        key)
          _arguments '1:action:(show export import rotate)'
          ;;
        snapshot)
          _arguments '1:action:(create restore list delete)'
          ;;
        config)
          _arguments '1:action:(export import validate)'
          ;;
        tag)
          _arguments '1:action:(add remove list find)'
          ;;
        template)
          _arguments '1:action:(list apply)'
          ;;
      esac
      ;;
  esac
}

_wangchuan
`;

export async function cmdCompletions(shell?: string): Promise<void> {
  switch (shell) {
    case 'bash':
      process.stdout.write(BASH_SCRIPT);
      break;
    case 'zsh':
      process.stdout.write(ZSH_SCRIPT);
      break;
    default:
      logger.error(t('completions.usage'));
      break;
  }
}
